#!/bin/sh
initFile=/opt/etc/init.d/S51dropbear
confFile=/opt/etc/config/dropbear.conf

_stop() {
  /opt/etc/init.d/S51dropbear stop
  kill -9 "$(pgrep /opt/sbin/dropbear)"
  rm -f /opt/var/run/dropbear.pid
}

_fix() {
  if grep -q "^PORT=22$" "$confFile"; then
    echo -e "Обнаружен 22 порт, меняем на 222"
    sed -i "s,PORT=22\$,PORT=222," "$confFile"
  fi
  if grep -q "^PIDFILE=\"/opt/var/run/dropbear.pid\"$" "$initFile"; then
    echo -e "Меняем местоположение dropbear.pid"
    sed -i 's,PIDFILE="/opt/var/run/dropbear.pid",PIDFILE="/var/run/dropbear.pid",g' "$initFile"
  fi
}

_start(){
  echo -e "Запускаем dropbear"
  "$initFile" start
}

_check() {
  echo -e "Проверяем запущен ли dropbear"
  "$initFile" status
  #pgrep /opt/sbin/dropbear
  busybox ps | grep /opt/sbin/dropbear | head -1
}

_print(){
  echo -e ""
  echo "Используйте для входа SSH:"
  getLanIp=$(busybox ifconfig br0 | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}')
  getPortDb=$(cat $confFile | cut -d= -f2)
  # stdPass - keenetic $1$6vKOV7zs$d2EqNYGvlBWEYoFD7FFkr0
  getStdPass=$(cat /opt/etc/passwd | grep root | cut -d: -f2)
  echo -e "IP: $getLanIp\nПорт: $getPortDb\n"
  if [ "$getStdPass" = '$1$6vKOV7zs$d2EqNYGvlBWEYoFD7FFkr0' ]; then
    echo -e "Логин: root\nПароль: keenetic\n"
  else
    echo -e "Логин: root\nПароль: Вы задавали сами. Отличается от стандартного - keenetic\n"
  fi
}

_reset_pass() {
  sed -i 's,'"$(cat passwd | grep 'root'|  awk -F: '{print $2}')",'$1$6vKOV7zs$d2EqNYGvlBWEYoFD7FFkr0,g' /opt/etc/passwd
}

_stop
_fix
_start
_check
[ "$RESET_PASS" == 1 ] && _reset_pass && _print || _print
