# Provider network interface, e.g. eth3
# general (krushaaa).conf
ISP_INTERFACE="ppp0"

# Startup arguments
NFQWS_BASE_ARGS="--lua-init=@/opt/etc/nfqws2/lua/zapret-lib.lua \
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-antidpi.lua \
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-auto.lua \
                 --blob=quic_lol:@/opt/etc/nfqws2/blobs/quic_initial_leagueoflegends.com.bin \
                 --blob=quic_rr1:@/opt/etc/nfqws2/blobs/quic_initial_rr1kyber2.bin
                 --blob=tls_one:@/opt/etc/nfqws2/blobs/tls_cf1.bin
                 --blob=discord_udp:@/opt/etc/nfqws2/blobs/ACTIVE_DISCORD_UDP.bin \
                 --blob=game_udp:@/opt/etc/nfqws2/blobs/ACTIVE_GAME_UDP.bin"

# HTTP(S) strategy  <- профиль --filter-tcp=80,443 из .bat
NFQWS_ARGS="--filter-tcp=80,443 --filter-l7=http,tls \
            --payload=tls_client_hello \
            --lua-desync=fake:blob=quic_lol:repeats=4:tcp_ts=-600000:tcp_ts_up
            --lua-desync=fake:blob=tls_one:repeats=4:tcp_ts=-600000:tcp_ts_up \
            --lua-desync=multidisorder:pos=2,midsld,endhost-1:repeats=4:seqovl=517:seqovl_pattern=tls_one \
            --payload=http_req \
            --lua-desync=fake:blob=tls_one:repeats=4:tcp_ts=-600000:tcp_ts_up \
            --lua-desync=multidisorder:pos=2,midsld,endhost-1:repeats=4:seqovl=517:seqovl_pattern=tls_one \ "
            
# QUIC strategy  <- профиль --filter-udp=443 из .bat
NFQWS_ARGS_QUIC="--filter-udp=443 --filter-l7=quic \
                 --payload=quic_initial \
                 --lua-desync=fake:blob=quic_rr1:repeats=4"

# UDP strategy  <- профиль Discord voice / STUN из .bat
NFQWS_ARGS_UDP="--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun \
                --payload=discord_ip_discovery,stun \
                --lua-desync=fake:blob=discord_udp:repeats=6"

# Working modes
MODE_LIST="--hostlist=/opt/etc/nfqws2/lists/user.list"
MODE_ALL="--hostlist-exclude=/opt/etc/nfqws2/lists/exclude.list"
MODE_AUTO="$MODE_LIST --hostlist-auto=/opt/etc/nfqws2/lists/auto.list --hostlist-auto-debug=/opt/var/log/nfqws2.log $MODE_ALL"
NFQWS_EXTRA_ARGS="$MODE_AUTO"

# IP-lists
NFQWS_ARGS_IPSET="--ipset=/opt/etc/nfqws2/lists/ipset.list --ipset-exclude=/opt/etc/nfqws2/lists/ipset_exclude.list"

# Custom arguments
NFQWS_ARGS_CUSTOM="
               
               #Discord
               --filter-tcp=2053,2083,2087,2096,8443 --filter-l7=tls \
               --hostlist-domains=discord.media \
               --payload=tls_client_hello \
               --lua-desync=fake:blob=tls_google:repeats=6:tcp_ts=-600000:tcp_ts_up \
               --new \
               --filter-tcp=443 --filter-l7=tls \
               --hostlist=/opt/etc/nfqws2/lists/google.list \
               --payload=tls_client_hello \
               --lua-desync=hostfakesplit:host=www.google.com:ip_id=zero:tcp_ts=-600000:tcp_ts_up "

# IPv6 support
IPV6_ENABLED=1

# TCP ports for iptables rules
TCP_PORTS=80,443,853,2053,2083,2087,2096,8443

# UDP ports for iptables rules
UDP_PORTS=443,853,680:700,19294:19344,50000:50100

# Keenetic policy name
POLICY_NAME="nfqws"
POLICY_EXCLUDE=0
LOG_LEVEL=0
LOG_DEBUG_PATH="@/opt/var/log/nfqws2-debug.log"
NFQUEUE_NUM=300
USER=nobody
CONFIG_VERSION=1

